workflows:
  build:
    name: MacOS arm64
    instance_type: mac_mini_m1
    triggering:
      events:
        - pull_request
    scripts:
      - name: Setup Java 11
        script: export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
      - name: Unit Tests
        script: mvn test

