name: OSX x64 Native Libs

on:
  push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download tokyocabinet
        run: setup/build-tokyocabinet-macos.sh
