name: Linux arm64

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04
          install: |
            apt -y update
            apt -y upgrade
            apt -y install build-essential libtool autoconf unzip wget curl
            wget https://raw.githubusercontent.com/jjlauer/vagrant-provision/master/linux/bootstrap-java.sh
            chmod +x bootstrap-java.sh
            ./bootstrap-java.sh --slim --default --url=https://cdn.azul.com/zulu-embedded/bin/zulu8.66.0.15-ca-jdk8.0.352-linux_aarch64.tar.gz
            wget https://raw.githubusercontent.com/jjlauer/vagrant-provision/master/linux/bootstrap-maven.sh
            chmod +x bootstrap-maven.sh
            ./bootstrap-maven.sh
          env: |
            PATH: $PATH:/usr/lib/jvm/current/bin:/opt/maven/current/bin
          run: |
            java -version
            mvn -version

      #- name: Set up Azul JDK 11
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: 11
      #    distribution: 'zulu'
      #    cache: 'maven'
      #- name: Test in Maven
      #  run: mvn test
