name: Linux MUSL x64
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Azul JDK 11
        uses: actions/setup-java@v3
        with:
          jdkFile: https://cdn.azul.com/zulu/bin/zulu11.60.19-ca-jdk11.0.17-linux_musl_x64.tar.gz
          cache: 'maven'
      - name: Test in Maven
        run: mvn test