name: Linux riscv64
on:
  - push
  - workflow_dispatch
jobs:
  bootstrap:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: riscv64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "~/.m2:/root/.m2" --volume "${PWD}:/mnt"
          install: |
            apt update
            apt -y install git curl wget gzip
            curl -s https://raw.githubusercontent.com/jjlauer/provisioning/master/linux/bootstrap-java.sh | sh -s -- --version=19
            curl -s https://raw.githubusercontent.com/jjlauer/provisioning/master/linux/bootstrap-maven.sh | sh
          run: |
            export PATH=$PATH:/usr/lib/jvm/current/bin:/opt/maven/current/bin
            cd /mnt
            mvn test